config/routes.rb
Rails.application.routes.draw do
  root "landing_page#index"
  devise_for :users, controllers: {registrations: "registrations"}
  resources :users, only: [:show] do
    get :followings, :followers, on: :member
  end
  resources :profile, only: [:index] do
    collection do
      get :recipes, :recipe_drafts, :cook_books, :settings
      patch :update_password, :update_username, :update_avatar, :disable_user_and_keep_data
      delete :delete_user_with_data
    end
  end
  resources :recipes do
    resources :comments
    patch :update_cook_books, on: :member
    patch :update_favourite, on: :member
  end
  resources :cook_books
  resources :recipe_scores, only: :create
  resources :follows, only: [:create, :destroy]
  resource :admin_panel, only: [:show] do
    collection do
      get :comments
      patch "/comment/:id", action: :comment_approve, as: :comment_approve
      delete "/comment/:id", action: :comment_reject, as: :comment_reject
    end
  end
  namespace :api do
    namespace :v1 do
      resources :recipes, only: [:show]
    end
  end
end

app/models/recipe.rb
# frozen_string_literal: true

class Recipe < ApplicationRecord
  with_options unless: :draft? do
    validates :preparation_description, presence: true
    validates :time_in_minutes_needed, presence: true
    validates :difficulty, presence: true
    validates :categories, length: {maximum: 5}, presence: true
    validates :ingredients_recipes, length: {minimum: 1}
  end
  validates :title, presence: true
  validates :status, presence: true
  validates :layout, presence: true
  validates_with RecipeImageValidator

  enum difficulty: {EASY: 0, MEDIUM: 1, HARD: 2}
  enum layout: {layout_1: 0, layout_2: 1, layout_3: 2}
  enum status: {draft: 0, published: 1}

  has_one_attached :image

  belongs_to :user

  has_many :recipe_scores,
    dependent: :destroy

  has_many :scorers,
    through: :recipe_scores,
    source: :user

  has_many :comments,
    dependent: :destroy

  has_many :ingredients_recipes,
    dependent: :destroy

  has_many :ingredients,
    through: :ingredients_recipes

  has_and_belongs_to_many :cook_books

  has_and_belongs_to_many :categories

  scope :published, -> { where(status: :published) }
  scope :drafted, -> { where(status: :draft) }
  scope :sort_by_default, ->(sort_kind, sort_order) {
    order(sort_kind => sort_order)
  }
  scope :sort_by_score, ->(sort_order, nulls_presence) {
    left_outer_joins(:recipe_scores)
      .select("recipes.*")
      .group("recipes.id")
      .order("avg(recipe_scores.score) #{sort_order} #{nulls_presence}")
  }
  scope :sort_by_kind_and_order, ->(sort_kind, sort_order) do
    case sort_kind
    when "title", "difficulty", "time_in_minutes_needed"
      sort_by_default(sort_kind, sort_order)
    when "score"
      nulls_presence = sort_order == "DESC" ? "NULLS LAST" : "NULLS FIRST"
      sort_by_score(sort_order, nulls_presence)
    end
  end

  accepts_nested_attributes_for :ingredients_recipes,
    allow_destroy: true,
    reject_if: ->(attributes) { attributes[:ingredient_name].blank? }

  def cook_books_update(cook_book_ids_raw, user)
    cook_book_id_strings = cook_book_ids_raw.filter { |cook_book_id| cook_book_id != "" }
    cook_book_ids = cook_book_id_strings.map { |cook_book_id| cook_book_id.to_i }
    if cook_book_ids.all? { |cook_book_id| user.cook_books.ids.include?(cook_book_id) }
      cook_books.delete(CookBook.where(user_id: user.id))
      cook_books << CookBook.where(id: cook_book_ids)
    else
      false
    end
  end

  def toggle_favourite(user)
    if user.favourites_cook_book.recipes.include?(self)
      user.favourites_cook_book.recipes.delete(self)
    else
      user.favourites_cook_book.recipes << self
    end
  end

  def average_score
    recipe_scores.average(:score).to_f.round(1)
  end

  def self.average_score
    joins(:recipe_scores)
      .pluck("avg(recipe_scores.score)")[0]
      .to_f.round(1)
  end

  def short_preparation_description(max_char = 175)
    return preparation_description if preparation_description.size <= max_char
    preparation_description[0...max_char - 3] + "..."
  end

  def resize_image
    return unless image.attached?

    path = attachment_changes["image"].attachable.tempfile.path
    v_filename = image.filename
    v_content_type = image.content_type
    resized_image = ImageProcessing::MiniMagick.source(path).resize_to_fill!(1280, 1920)
    image.attach(io: File.open(resized_image.path), filename: v_filename, content_type: v_content_type)
  end
end

app/controllers/api/v1/recipes_controller.rb
module Api
  module V1
    class RecipesController < ActionController::API
      include Api::Concerns::ErrorSerializer

      def show
        recipe = Recipe.find(params[:id])

        render json: {
          data: ActiveModelSerializers::SerializableResource.new(recipe, serializer: RecipeSerializer),
          status: 200,
          type: "Success"
        }
      end
    end
  end
end

app/controllers/recipes_controller.rb
# frozen_string_literal: true

class RecipesController < ApplicationController
  DEFAULT_SORT_KIND = "title"
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_recipe, except: %i[index new create]
  before_action :validate_sort_params!, only: [:index]

  def index
    @sort_order = sort_order
    @sort_kind = sort_kind
    recipes = Recipe.published.sort_by_kind_and_order(@sort_kind, @sort_order)
    @pagy, @recipes = pagy(recipes, items: per_page)
  end

  def show
    @recipe = Recipe.find_by(id: params[:id])
    if @recipe.draft? && @recipe.user != current_user
      respond_to do |format|
        format.html { redirect_to recipes_path, notice: t(".warning") }
      end
    else
      @ingredients_recipe = @recipe.ingredients_recipes
      gon.avgScore = @recipe.average_score
    end
  end

  def new
    @recipe = Recipe.new
    @ingredients = []
  end

  def edit
    @recipe = Recipe.find_by(id: params[:id])
    if @recipe.draft? && @recipe.user != current_user
      respond_to do |format|
        format.html { redirect_to recipes_path, notice: t(".warning") }
      end
    else
      set_ingredients
    end
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    @recipe.resize_image if params[:recipe].key?(:image)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: t(".notice") }
      else
        @recipe.errors.full_messages.each do |e|
          flash.now[:error] = e
        end
        @ingredients = []
        if recipe_params.has_key?(:ingredients_recipes_attributes)
          recipe_params[:ingredients_recipes_attributes].values.each do |i|
            if i[:_destroy] != 1
              @ingredients.append(i.except(:_destroy))
            end
          end
        end
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])

    @recipe.destroy if @recipe.user == current_user || current_user.admin?

    respond_to do |format|
      format.html { redirect_to recipes_path, notice: t(".notice") }
    end
  end

  def update
    params = recipe_params
    if !params.key?(:category_ids)
      params[:category_ids] = []
    end
    if !params.key?(:ingredients_recipes_attributes)
      IngredientsRecipe.where(recipe_id: @recipe.id).destroy_all
      params[:ingredients_recipes_attributes] = {}
    end
    @recipe.attributes = params
    @recipe.resize_image if params.key?(:image)
    respond_to do |format|
      if @recipe.valid? && params[:ingredients_recipes_attributes] != {}
        IngredientsRecipe.where(recipe_id: @recipe.id).destroy_all
        @recipe.save
        format.html { redirect_to @recipe, notice: t(".notice") }
      else
        set_ingredients
        @recipe.errors.full_messages.each do |e|
          flash.now[:error] = e
        end
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def update_cook_books
    if @recipe.cook_books_update(cook_books_params[:cook_book_ids], current_user)
      flash[:notice] = t(".notice")
    else
      flash[:alert] = t(".alert")
    end
    redirect_back(fallback_location: recipes_path)
  end

  def update_favourite
    @recipe.toggle_favourite(current_user)
    flash[:notice] = t(".notice")
    redirect_to(@recipe)
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:image, :title, :preparation_description, :time_in_minutes_needed, :difficulty, :user_id, :status, :layout, category_ids: [],
      ingredients_recipes_attributes: [:id, :ingredient_name, :quantity, :unit, :_destroy])
  end

  def cook_books_params
    params.require(:recipe).permit(cook_book_ids: [])
  end

  def set_ingredients
    @ingredients = []
    IngredientsRecipe.where("recipe_id=#{@recipe.id}").each do |i|
      j = {ingredient_name: i.ingredient.name, quantity: i.quantity, unit: IngredientsRecipe.units[i.unit]}
      @ingredients.append(j)
    end
  end

  def validate_sort_params!
    sort_params = params.permit(:page, :items, :kind, :order)
    validator = RecipesSortParamsValidator.new(sort_params)
    return if validator.valid?
    redirect_to recipes_path
  end

  def sort_kind
    params[:kind].presence || DEFAULT_SORT_KIND
  end
end

app/helpers/recipe_helper.rb
module RecipeHelper
  IMAGE_CLASS = "flex-none rounded-lg object-cover bg-gray-100"
  IMAGE_ALT = "image showing dish"
  IMAGE_DEFAULT = "https://res.cloudinary.com/hp7f0176d/image/upload/v1629832221/sample/default_recipe_u9wld9.png"
  IMAGE_THUMBNAIL_DEFAULT = "https://res.cloudinary.com/hp7f0176d/image/upload/v1629832231/sample/default_recipe_thumbnail_yarrcr.png"

  def recipes_sort_options
    {
      kind: {
        "#{t("sort.by_title")}": "title",
        "#{t("sort.by_score")}": "score",
        "#{t("sort.by_time")}": "time_in_minutes_needed",
        "#{t("sort.by_difficulty")}": "difficulty"
      },
      order: {
        "#{t("sort.ascending")}": "ASC",
        "#{t("sort.descending")}": "DESC"
      }
    }
  end

  def recipe_image_for_index(recipe)
    if recipe.image.attached?
      image_tag(recipe.image.variant(resize_to_fill: [100, 100]), class: IMAGE_CLASS, alt: IMAGE_ALT)
    else
      image_tag(IMAGE_THUMBNAIL_DEFAULT, class: IMAGE_CLASS)
    end
  end

  def recipe_image_for_layout1(recipe)
    if recipe.image.attached?
      image_tag(recipe.image.variant(resize_to_fill: [1280, 1600]), class: IMAGE_CLASS, alt: IMAGE_ALT)
    else
      image_tag(IMAGE_DEFAULT, class: IMAGE_CLASS)
    end
  end

  def recipe_image_for_layout2(recipe)
    if recipe.image.attached?
      image_tag(recipe.image.variant(resize_to_fill: [1280, 256]), class: IMAGE_CLASS, alt: IMAGE_ALT)
    else
      image_tag(IMAGE_DEFAULT, class: IMAGE_CLASS)
    end
  end

  def recipe_image_for_layout3(recipe)
    if recipe.image.attached?
      image_tag(recipe.image, class: IMAGE_CLASS, alt: IMAGE_ALT)
    else
      image_tag(IMAGE_DEFAULT, class: IMAGE_CLASS)
    end
  end

  def authorize_recipe_action_links?(recipe)
    user_signed_in? && (recipe.user == current_user || current_user.admin?)
  end
end

app/views/recipes/_description.html.slim
.m-16.flex.flex-col
  .pb-3.text-lg 
    = @recipe.preparation_description

app/views/recipes/_form_cook_books.html.slim
= form_with(url: update_cook_books_recipe_path(form_data[:model]), model: form_data[:model], local: true) do |f|
  .checkbox-list
    = f.collection_check_boxes(:cook_book_ids, current_user.cook_books, :id, :title) do |b|
      .input-checkbox
        = b.check_box id: "#{id}-#{b.object.id}"
        = b.label for: "#{id}-#{b.object.id}"
          .label-text
            = b.text
          .checkboxer
            = render "shared/check"
  .flex.flex-col.bg-gray-50.px-4.py-2.sm:px-6.sm:flex-row-reverse
    = f.submit t("recipes.update_cook_books.action"), class: "btn-secondary"
    button.btn-primary type="button" onclick="toggleDisplay('#{id}')"
      = t("buttons.cancel")
      

app/views/recipes/_header.html.slim
.min-h-10v.flex.flex-col 
  .w-full.h-2/3.flex.flex-row.justify-between.items-end
    .text-3xl.font-semibold
      - if @recipe.draft? 
        = @recipe.title + " (draft)"
      - else 
        = @recipe.title
    .text-xl
      = @recipe.difficulty.capitalize
  .w-full.text-sm.text-left
    | #{@recipe.time_in_minutes_needed} min.

app/views/recipes/_layout_1.html.slim
.col-start-3.col-span-13.h-92v.flex.flex-row
  .w-1/2.flex.flex-col
    = render 'header'
    .rounded-md.overflow-hidden.shadow-lg
      .aspect-w-4.aspect-h-5
        = recipe_image_for_layout1(@recipe)
    .h-8v
  .w-1/2.flex.flex-col.items-center data-controller="recipe"
    .min-h-10v.flex.flex-col.justify-center
      ul#recipe-nav.flex.flex-row.items-center.text-mustard.font-bold.text-2xl.rounded-md 
        li#ingredients-button.cursor-pointer.py-2.px-4.bg-gray-900.hover:bg-gray-700.rounded-l-md.selected data-action="click->recipe#ingredients" data-recipe-target="ingredients_button"
          = t("recipes.show.ingredients")
        li#method-button.cursor-pointer.py-2.px-4.bg-gray-900.hover:bg-gray-700 data-action="click->recipe#method" data-recipe-target="method_button"
          = t("recipes.show.method")
        li#comments-button.cursor-pointer.py-2.px-4.bg-gray-900.hover:bg-gray-700.rounded-r-md data-action="click->recipe#comments" data-recipe-target="comments_button"
          = t("recipes.show.comments")
    #recipe-field.w-full.h-full.border-r-2.border-mustard
      #ingredients-content data-recipe-target="ingredients_content"
        .m-16
          = render @ingredients_recipe, position: :center
      #method-content.hidden data-recipe-target="method_content"
        .text-center 
          = render 'description'
      #comments-content.hidden.h-74v.overflow-y-scroll.scrollbar-hide data-recipe-target="comments_content"
        = render "comments/comments_with_form"
    .min-h-8v.w-full

app/views/recipes/_layout_2.html.slim
.col-start-3.col-span-13.flex.flex-col
  = render 'header'
  .h-74v.overflow-y-scroll.scrollbar-hide
    .min-h-82v
      .w-full.rounded-md.overflow-hidden.shadow-lg
        .aspect-w-5.aspect-h-1
           = recipe_image_for_layout2(@recipe)
      .flex.flex-row.mt-10
        .w-1/2.border-r-2.border-mustard
          .text-3xl.text-center.mt-6
            = t("recipes.show.ingredients")
          .m-16
            = render @ingredients_recipe, position: :center
        .w-1/2
          .text-3xl.text-center.mt-6
            = t("recipes.show.method")
          .text-center 
            = render 'description'
    .min-h-74v
      = render "comments/comments_with_form"
    .min-h-8v.w-full

app/views/recipes/_layout_3.html.slim
.col-start-3.col-span-13.flex.flex-row
  .w-3/8.flex.flex-col.h-92v
    = render 'header'
    .rounded-md.overflow-hidden.shadow-lg
      .aspect-w-6.aspect-h-9
        = recipe_image_for_layout3(@recipe)
    .h-8v
  .w-5/8.flex.flex-col
    .min-h-10v
    .h-74v.overflow-y-scroll.scrollbar-hide
      .min-h-82v.flex.flex-col
        .flex.flex-row.flex-grow 
          .w-2/5.min-h-full.border-r-2.border-mustard
            .text-3xl.text-left.ml-16
              = t("recipes.show.ingredients")
            .m-16
              = render @ingredients_recipe, position: :start
          .w-3/5 
            .text-3xl.text-left.ml-16
              = t("recipes.show.method")
            = render 'description'
        .h-8v
      .min-h-74v
        = render "comments/comments_with_form"
    .min-h-8v.w-full

app/views/recipes/_recipe.html.slim
article.recipe.p-4.flex.space-x-4.bg-white.shadow-lg.rounded-lg.my-3
  .max-h-100-px.w-100.flex-none.rounded-lg
    = recipe_image_for_index(recipe)
  .flex-1
    = link_to recipe.title, recipe_path(recipe), class: "text-lg font-semibold text-black mb-0.5 break-all hover:opacity-75"
    dl.flex.flex-row.text-sm.font-medium.whitespace-pre
      dd 
        = recipe.categories.map{|c| c.name}.join(", ")
      |  • 
      dd
        = recipe.difficulty.downcase
      |  • 
      dd
        = "#{recipe.time_in_minutes_needed} #{t("minutes")}"
    dl.flex.text-sm.font-medium.whitespace-pre
      dd.italic
        = link_to recipe.user.username, user_path(recipe.user), class: "hover:opacity-75"
  .flex.items-start
    .px-3.py-1.rounded-full.bg-mustard-50.border-2.border-mustard-100.flex.items-center.space-x-3
      - if recipe.recipe_scores.empty?
        = render "shared/star", filled: false, size: 23
        dd - 
      - else
        = render "shared/star", filled: :full, size: 23
        dd #{recipe.average_score}
    
    - if user_signed_in?
        - id = "modal_add_recipe#{recipe.id}"

        input.drop-btn-hidden type="radio" name="dropdown" id="dropdown_recipe#{recipe.id}"
        .dropdown
          .mx-2
            button type="button" onclick="uncheckDropdown('dropdown_recipe#{recipe.id}')"
              .drop-btn
                = render "shared/dots_vertical"
          .drop-menu tabindex="-1"
            button.drop-item type="button" onclick="toggleDisplay('#{id}')" tabindex="-1"
              = t("cook_book_recipes.create.action")
            py-1
              - if authorize_recipe_action_links?(recipe)
                = link_to t("recipes.edit.action"), edit_recipe_path(recipe), class: "drop-item", tab_index: "-1"
                = link_to t("recipes.destroy.action"), recipe_path(recipe), method: :delete, data: {confirm: t("confirm")}, class: "drop-item", tab_index: "-1"
        = render "shared/modal", id: id, body: "recipes/form_cook_books", form_data: { model: recipe }

app/views/recipes/_right_margin.html.slim
.col-start-16.h-92v.flex.flex-col.justify-items-end
  .flex-grow
  - if authorize_recipe_action_links?(@recipe)
    .flex.flex-col.mx-4.mb-8v
      = link_to t("recipes.edit.action"), edit_recipe_url(@recipe), class: "text-center btn-primary"
      = link_to t("recipes.destroy.action"), recipe_url(@recipe), method: :delete, class: "text-center btn-primary"

app/views/recipes/_sort_form.html.slim
- sort_options = recipes_sort_options

= form_tag(recipes_path, method: "GET") do
  .flex
    .input-select
      .relative
        = select_tag :kind, options_for_select(sort_options[:kind], @sort_kind), onchange: "this.form.submit()"
        .selector
          = render "shared/arrow_down"
    .input-select
      .relative
        = select_tag :order, options_for_select(sort_options[:order], @sort_order), onchange: "this.form.submit()"
        .selector
          = render "shared/arrow_down"

app/views/recipes/edit.html.slim
.flex.flex-grow.w-full.mt-5
  .w-4/5.m-auto.content-center
		= form_with(model: @recipe, local:true, url: "/recipes/#{@recipe.id}", method: :patch, class: "bg-white shadow-md rounded px-6 pt-6 pb-12 mb-12") do |f|
			.mb-4.input-file-white
			  = f.label :image, value: "Image (optional)"
			  = f.file_field :image, accept: "image/png,image/jpeg"
			.mb-4.input-text-white
			  = f.label :title
			  = f.text_field :title
			.mb-4.input-text-white
			  = f.label :preparation_description
			  = f.text_area :preparation_description
			.mb-4.input-text-white
			  = f.label :time_in_minutes_needed, "Time needed (in minutes)"
			  = f.number_field :time_in_minutes_needed
			.mb-4.input-select-white
			  = f.label :difficulty
			  .relative
			    = f.select :difficulty, Recipe.difficulties.map { |key, value| [key.capitalize, key] }
				.selector
         		  = render "shared/arrow_down"
			.mb-4.input-select-white
			  = f.label :layout
			  .relative
			  	= f.select :layout, Recipe.layouts.keys
				.selector
         		  = render "shared/arrow_down"
			.m-3.input-base
				p class="block text-gray-700 text-sm font-bold mb-2" Categories:
				.flex.flex-wrap.border.p-4.border-gray-300.rounded-md.shadow-md
						- categories = @recipe.categories.map(&:id)
						- Category.all.each do |cat|
								.p-3.
										= check_box_tag "recipe[category_ids][]", cat.id, categories.include?(cat.id), class: "mr-1"
										= label_tag :category_id, cat.name
			.m-3.border.p-4.border-gray-300.rounded-md.shadow-md
					- html_options = link_to_add__ingredients_fields t('buttons.add_ingredient'), f, :ingredients_recipes, { partial: 'ingredient_fields' }
					p.text-lg.text-gray-700.font-bold.mb-3 Ingredients:
					- for link in @ingredients do 
							= field_set_tag nil, data_form: html_options['data-form-prepend'], data_ingredient: link[:ingredient_name], data_quantity: link[:quantity], data_unit: link[:unit]
					= link_to t("buttons.add_ingredient"), "#", html_options
			.ml-3
				= f.hidden_field :status
                - if @recipe.draft?
                    = f.submit(t('buttons.update_and_publish'), onclick: "document.getElementById('recipe_status').value = 'published'", class: "btn-secondary")
                - else 
                    = f.submit(t('buttons.update_and_save_as_draft'), onclick: "document.getElementById('recipe_status').value = 'draft'", class: "btn-secondary")
                = f.submit(t('buttons.update_recipe'), class: "btn-secondary")

= javascript_pack_tag "add_ingredient"

app/views/recipes/index.html.slim
.px-10.mt-3
  .flex.justify-between.my-2.px-3
    .flex.items-center
      == pagy_nav(@pagy) if @pagy.pages > 1
    = render "sort_form"
  - if @recipes.present?
    = render @recipes
  - else 
    p.text-center.mt-4
      = t("recipes.not_found")
  .flex.justify-center.my-2
    == pagy_nav(@pagy) if @pagy.pages > 1

app/views/recipes/new.html.slim
.flex.flex-grow.w-full.mt-5
    .w-4/5.m-auto.content-center
      = form_with(model: @recipe, local:true, url: "/recipes", method: :post, class: "bg-white shadow-md rounded px-6 pt-6 pb-12 mb-12") do |f|
            .mb-4.input-file-white
			  = f.label :image, value: "Image (optional)"
			  = f.file_field :image, accept: "image/png,image/jpeg"
			.mb-4.input-text-white
			  = f.label :title
			  = f.text_field :title
			.mb-4.input-text-white
			  = f.label :preparation_description
			  = f.text_area :preparation_description
			.mb-4.input-text-white
			  = f.label :time_in_minutes_needed, "Time needed (in minutes)"
			  = f.number_field :time_in_minutes_needed
			.mb-4.input-select-white
			  = f.label :difficulty
			  .relative
			    = f.select :difficulty, Recipe.difficulties.map { |key, value| [key.capitalize, key] }
				.selector
         		  = render "shared/arrow_down"
			.mb-4.input-select-white
			  = f.label :layout
			  .relative
			  	= f.select :layout, Recipe.layouts.keys
				.selector
         		  = render "shared/arrow_down"
            .m-3.input-base
							p class="block text-gray-700 text-sm font-bold mb-2" Categories:
							.flex.flex-wrap.border.p-4.border-gray-300.rounded-md.shadow-md
								- categories = @recipe.categories.map { |cat| cat.id }
								- Category.all.each do |cat|
									.p-3.
										= check_box_tag "recipe[category_ids][]", cat.id, categories.include?(cat.id), class: "mr-1"
										= label_tag :category_id, cat.name
            .m-3.border.p-4.border-gray-300.rounded-md.shadow-md
                - html_options = link_to_add__ingredients_fields t('buttons.add_ingredient'), f, :ingredients_recipes, { partial: 'ingredient_fields' }
                p.text-lg.text-gray-700.font-bold.mb-3 Ingredients:
                - for link in @ingredients do 
                    = field_set_tag nil, data_form: html_options['data-form-prepend'], data_ingredient: link[:ingredient_name], data_quantity: link[:quantity], data_unit: link[:unit]
                = link_to t("buttons.add_ingredient"), "#", html_options
            .ml-3
                = f.hidden_field :status, value: "draft"
                = f.submit(t('buttons.save_recipe_as_draft'), id: "draft_submit", class: "btn-secondary")
                = f.submit(t('buttons.publish_recipe'), onclick: "document.getElementById('recipe_status').value = 'published'", id: "save_submit", class: "btn-secondary")

= javascript_pack_tag "add_ingredient"

app/views/recipes/show.html.slim
.grid.grid-cols-16.h-92v
  = render 'recipe_scores/score_modal' if current_user
  = render 'left_panel'
  = render @recipe.layout
  = render 'right_margin'

app/views/recipes/update.html.slim
h1 Recipe#update
p Find me in app/views/recipe/update.html.slim