config/routes.rb
Rails.application.routes.draw do
  root "landing_page#index"
  devise_for :users, controllers: {registrations: "registrations"}
  resources :users, only: [:show] do
    get :followings, :followers, on: :member
  end
  resources :profile, only: [:index] do
    collection do
      get :recipes, :recipe_drafts, :cook_books, :settings
      patch :update_password, :update_username, :update_avatar, :disable_user_and_keep_data
      delete :delete_user_with_data
    end
  end
  resources :recipes do
    resources :comments
    patch :update_cook_books, on: :member
    patch :update_favourite, on: :member
  end
  resources :cook_books
  resources :recipe_scores, only: :create
  resources :follows, only: [:create, :destroy]
  resource :admin_panel, only: [:show] do
    collection do
      get :comments
      patch "/comment/:id", action: :comment_approve, as: :comment_approve
      delete "/comment/:id", action: :comment_reject, as: :comment_reject
    end
  end
  namespace :api do
    namespace :v1 do
      resources :recipes, only: [:show]
    end
  end
end

app/models/follow.rb
class Follow < ApplicationRecord
  # The user giving the follow
  belongs_to :follower,
    class_name: "User"
  # The user being followed
  belongs_to :followed_user,
    class_name: "User"

  after_create_commit -> { FollowServices::Broadcaster.new(self).notify_about_new_follower }

  def send_notification_email
    NotificationMailer.follow_notification(followed_user, follower).deliver_now unless followed_user.disabled?
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :authenticate_user!

  def create
    @user = User.find(params[:followed_user_id])
    @follow = current_user.follow(@user)
    flash[:notice] = t(".notice")
    @follow.send_notification_email if @user != current_user
    redirect_back fallback_location: @user
  end

  def destroy
    @user = Follow.find_by(followed_user_id: params[:id]).followed_user
    current_user.unfollow(@user)
    flash[:notice] = t(".notice")
    redirect_back fallback_location: @user
  end
end

app/views/follows/_follow.html.slim
= form_for(current_user.given_follows.build) do |f|
  = hidden_field_tag :followed_user_id, user.id
  = f.submit t("follows.create.action"), class: "btn-primary"

app/views/follows/_stats.html.slim
- followings_count = user.followings.count
- followers_count = user.followers.count

.space-x-4.font-medium.text-gray-500.flex#follows-stats
  .hover:opacity-40#followings
    - if followings_count == 1
      = link_to t("follows.followings.one"), followings_user_path(user)
    - else
      = link_to t("follows.followings.other", count: followings_count), followings_user_path(user)

  .hover:opacity-40#followers
    - if followers_count == 1
      = link_to t("follows.followers.one"), followers_user_path(user)
    - else
      = link_to t("follows.followers.other", count: followers_count), followers_user_path(user)

app/views/follows/_unfollow.html.slim
button.btn-primary type="button"
  = link_to t("follows.destroy.action"), follow_path(user), method: :delete, data: {confirm: t("confirm")}