config/routes.rb
Rails.application.routes.draw do
  root "landing_page#index"
  devise_for :users, controllers: {registrations: "registrations"}
  resources :users, only: [:show] do
    get :followings, :followers, on: :member
  end
  resources :profile, only: [:index] do
    collection do
      get :recipes, :recipe_drafts, :cook_books, :settings
      patch :update_password, :update_username, :update_avatar, :disable_user_and_keep_data
      delete :delete_user_with_data
    end
  end
  resources :recipes do
    resources :comments
    patch :update_cook_books, on: :member
    patch :update_favourite, on: :member
  end
  resources :cook_books
  resources :recipe_scores, only: :create
  resources :follows, only: [:create, :destroy]
  resource :admin_panel, only: [:show] do
    collection do
      get :comments
      patch "/comment/:id", action: :comment_approve, as: :comment_approve
      delete "/comment/:id", action: :comment_reject, as: :comment_reject
    end
  end
  namespace :api do
    namespace :v1 do
      resources :recipes, only: [:show]
    end
  end
end

app/models/cook_book.rb
class CookBook < ApplicationRecord
  enum visibility: {public: 0, private: 1, followers: 2}, _prefix: true

  validates_presence_of :title
  validates_inclusion_of :visibility, in: visibilities
  validates_inclusion_of :favourite, in: [true, false]

  belongs_to :user
  has_and_belongs_to_many :recipes

  scope :for_public, -> { where(visibility: :public) }
  scope :for_followers, -> { where(visibility: :followers) }
  scope :for_public_and_followers, -> { where(visibility: [:public, :followers]) }
  scope :for_specific_followers, ->(followings_ids) do
    where(visibility: :followers, user_id: followings_ids)
  end

  def recipes_visible_for_user(user)
    if user.present?
      recipes.published.or(recipes.drafted.where(user_id: user.id))
    else
      recipes.published
    end
  end

  def self.visibilities_strings
    CookBook.visibilities.map { |key, value| [I18n.t("cook_books.visibilities.#{key}"), key] }
  end
end

app/controllers/cook_books_controller.rb
# frozen_string_literal: true

class CookBooksController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  before_action :set_visibilities, only: [:index]
  before_action :set_cook_book, only: [:show, :edit, :destroy]

  def index
    @cook_book = CookBook.new
    @cook_books = policy_scope(CookBook).for_public_and_followers
    @pagy, @cook_books = pagy(@cook_books, items: per_page)
  end

  def show
    @cook_book = CookBook.find_by(id: params[:id])
    @recipes = @cook_book.recipes
  end

  def edit
  end

  def destroy
    authorize @cook_book
    if @cook_book.destroy
      flash[:notice] = t(".notice")
    else
      flash[:alert] = t(".alert")
    end
    redirect_back(fallback_location: cook_books_path)
  end

  def create
    @cook_book = CookBook.new(cook_book_params)
    @cook_book.user = current_user
    if @cook_book.save
      flash[:notice] = t(".notice")
    elsif @cook_book.valid?
      flash[:alert] = t(".alert")
    else
      flash[:alert] = @cook_book.errors.full_messages[0]
    end
    redirect_to(cook_books_profile_index_path)
  end

  private

  def set_visibilities
    @visibilities = CookBook.visibilities_strings
  end

  def set_cook_book
    @cook_book = policy_scope(CookBook).find(params[:id])
  end

  def cook_book_params
    params.require(:cook_book).permit(:title, :visibility)
  end
end

app/helpers/cook_book_helper.rb
module CookBookHelper
  def cook_book_recipes_text(recipes)
    recipes_count = recipes.count
    recipes_titles = recipes[0..2].map { |recipe| recipe.title }
    text = recipes_titles.join(", ")
    text += t("cook_books.recipes_inside", count: recipes_count - 3) if recipes_count > 3
    recipes_count > 0 ? text : t("recipes.not_found")
  end

  def cook_book_visibility_svg(visibility)
    visibility == "public" ? "" : render("shared/#{visibility}_cook_book")
  end

  def authorize_cook_book_dropdown?(cook_book)
    user_signed_in? && (cook_book.user == current_user || current_user.admin?)
  end
end

app/views/cook_books/_cook_book.html.slim
- recipes = cook_book.recipes_visible_for_user(current_user)
article.relative.my-3.w-full.lg:w-1/2.2xl:w-1/3.cook-book
  .mx-3.px-4.py-5.bg-white.shadow-lg.rounded-lg.flex.flex-col.items-center.text-center.h-full
    = link_to cook_book.title, cook_book_path(cook_book), class: "text-lg font-semibold text-black break-all hover:opacity-75"
    .italic
      = link_to cook_book.user.username, user_path(cook_book.user), class: "hover:opacity-75"
    .flex.w-full.space-x-4.mt-2
      - recipes[0..2].each do |recipe|
        .flex-grow.flex.justify-center
          = link_to image_tag("/images/default_recipe.png", class: "rounded-2xl object-cover h-24 w-auto transition-opacity opacity-75 hover:opacity-100", alt: ""), recipe_path(recipe)
    .text-gray-700.text-lg.px-16.mt-4
      = cook_book_recipes_text(recipes)
  .absolute.top-0.left-0.ml-5.mt-2
    = cook_book_visibility_svg(cook_book.visibility)
  .absolute.top-0.right-0.mr-4.mt-2
    - if authorize_cook_book_dropdown?(cook_book)
      input.drop-btn-hidden type="radio" name="dropdown" id="dropdown_cook_book#{cook_book.id}"
      .dropdown
        .mx-2
          button type="button" onclick="uncheckDropdown('dropdown_cook_book#{cook_book.id}')"
            .drop-btn
              = render "shared/dots_vertical"
        .drop-menu tabindex="-1"
          = link_to t("cook_books.edit.action"), edit_cook_book_path(cook_book), class: "drop-item", tab_index: "-1"
          - unless cook_book.favourite
            = link_to t("cook_books.destroy.action"), cook_book_path(cook_book), method: :delete, data: {confirm: t("confirm")}, class: "drop-item", tab_index: "-1"

app/views/cook_books/edit.html.slim
.mt-5.text-2xl.text-center
  = @cook_book.title

app/views/cook_books/index.html.slim
.px-10.mt-3
  .flex.justify-center.my-2
    == pagy_nav(@pagy) if @pagy.pages > 1
  - if @cook_books.present?
    .flex.flex-wrap.justify-center.items-stretch
      = render @cook_books
  - else 
    p.text-center.mt-5
      = t("cook_books.not_found")
  .flex.justify-center.my-2
    == pagy_nav(@pagy) if @pagy.pages > 1

app/views/cook_books/show.html.slim
.container.mx-auto 
  .mt-8.mb-2.text-center.text-4xl.font-bold
    = @cook_book.title
  .text_sm.flex.flex-row.justify-center
    | #{t("cook_books.show.created")} #{@cook_book.user.username}
  .flex.flex-col
    = render @recipes 