config/routes.rb
Rails.application.routes.draw do
  root "landing_page#index"
  devise_for :users, controllers: {registrations: "registrations"}
  resources :users, only: [:show] do
    get :followings, :followers, on: :member
  end
  resources :profile, only: [:index] do
    collection do
      get :recipes, :recipe_drafts, :cook_books, :settings
      patch :update_password, :update_username, :update_avatar, :disable_user_and_keep_data
      delete :delete_user_with_data
    end
  end
  resources :recipes do
    resources :comments
    patch :update_cook_books, on: :member
    patch :update_favourite, on: :member
  end
  resources :cook_books
  resources :recipe_scores, only: :create
  resources :follows, only: [:create, :destroy]
  resource :admin_panel, only: [:show] do
    collection do
      get :comments
      patch "/comment/:id", action: :comment_approve, as: :comment_approve
      delete "/comment/:id", action: :comment_reject, as: :comment_reject
    end
  end
  namespace :api do
    namespace :v1 do
      resources :recipes, only: [:show]
    end
  end
end

app/helpers/layouts_helper.rb
module LayoutsHelper
  def btn_nav_class_for_recipes(path)
    request.path.match(/^#{path}/) && request.path != new_recipe_path ? "btn-nav-active" : "btn-nav"
  end

  def btn_nav_class_overall(path)
    /^#{path}/.match?(request.path) ? "btn-nav-active" : "btn-nav"
  end
end

app/views/layouts/_flash_messages.html.slim
- flash.each do |name, msg|
  - if name == "notice"
    .bg-green-100.border.border-green-400.text-green-700.px-4.py-3.rounded.relative.block#flash-success onclick="toggleDisplay('flash-success', 'block')"
      = msg
      span.absolute.top-0.bottom-0.right-0.px-4.py-3
        a href="#" id="close"
          svg.fill-current.h-6.w-6.text-green-500 role="button" viewBox="0 0 20 20" id="icon-close"
            use xlink:href="#icon-close"
            title Close
            path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"
  - else
    .bg-red-100.border.border-red-400.text-red-700.px-4.py-3.rounded.relative.block#flash-error onclick="toggleDisplay('flash-error', 'block')"
      strong
        = msg
      span.absolute.top-0.bottom-0.right-0.px-4.py-3
        a href="#" id="close"
          svg.fill-current.h-6.w-6.text-red-500 role="button" viewBox="0 0 20 20" id="icon-close"
            use xlink:href="#icon-close"
            title Close
            path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"

app/views/layouts/_navbar.html.slim
.fixed.top-0.z-40.w-full.flex.justify-between.bg-black.px-6.py-2.h-14
  .flex.space-x-5.items-center
    = link_to image_tag("/images/logo.png", alt: ""), root_path, class: "w-2/12 h-2/12 mr-3 hover:opacity-75"
    = link_to t("buttons.recipes"), recipes_path, class: btn_nav_class_for_recipes(recipes_path)
    = link_to t("buttons.cook_books"), cook_books_path, class: btn_nav_class_overall(cook_books_path)
  .flex.space-x-5.items-center
    - if user_signed_in?
      = link_to t("buttons.add_new_recipe"), new_recipe_path, class: btn_nav_class_overall(new_recipe_path)
      input.drop-btn-hidden.ml-5 type="radio" name="dropdown" id="dropdown_navbar"
      .dropdown
        button.dark-drop-btn onclick="uncheckDropdown('dropdown_navbar')" id="dropdown_navbar_button"
          = image_tag(current_user.default_or_attached_avatar, class:"w-8 h-8 object-cover rounded-full border border-gray-600", id:"navbar_user_avatar_image")
          .px-3
            = current_user.username
          = render "shared/arrow_down", filled: "white"
        .dark-drop-menu tabindex="-1"
          - if current_user.admin?
            = link_to t("buttons.admin_panel"), admin_panel_path, class: "dark-drop-item"
          = link_to t("buttons.dashboard"), profile_index_path, class: "dark-drop-item"
          = link_to t("buttons.my_profile"), user_path(current_user), class: "dark-drop-item"
          = link_to t("buttons.log_out"), destroy_user_session_path, method: :delete, class: "dark-drop-item"
    - else
      = link_to t("buttons.log_in"), new_user_session_path, class: btn_nav_class_overall(new_user_session_path)
      = link_to t("buttons.sign_up"), new_user_registration_path, class: btn_nav_class_overall(new_user_registration_path)

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | RecipeBook
    = include_gon
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body.flex.flex-col.h-screen.bg-gray-100
    = render "layouts/navbar"
    - if current_user
      = render partial: "shared/notification", locals: { user_id: current_user.id }
    .flex-grow.flex.flex-col.mt-14
      = render "layouts/flash_messages"
      = yield